# Nome das Ações:  
nome : jogo da cobra

# Controlador do tempo que será feito a atualização dos arquivos.
em :
  cronograma :
      # Será atualizado a cada 5 horas.
-cron     : " 0 */5 * * * "

# Permite executar na lista de ações (utilizado para testes de compilação).
  workflow_dispatch :

#Regras _
empregos :
  construir :
    run-on : ubuntu-latest
    passos :

    # Verifica o repositório em $GITHUB_WORKSHOP, para que seu trabalho possa acessá-lo
      - usa : actions/checkout@v2

    # Repositório que será utilizado para gerar os arquivos.
      - usa : Platane/snk@master
        id : cobra-gif
        com :
          github_user_name : C4i0LUAN # Seu usuario
          gif_out_path : dist/github-contribution-grid-snake.gif
          svg_out_path : dist/github-contribution-grid-snake.svg

      - executar : git status

      # Para como atualizações.
      - nome : Empurre alterações
        usa : ad-m/github-push-action@master
        com :
          github_token : ${{ secrets.GITHUB_TOKEN }}
          ramo : mestre
          força : verdade

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          # a ramificação de saída que mencionamos acima
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
